### PR TITLE
[core][directory] Adding scandir as dependency

### PR DESCRIPTION
**Pull request by tebriel**

### CODE REVIEW

**Comment by tebriel** [comment]
Corresponds to https://github.com/DataDog/omnibus-software/pull/36

**Comment by tebriel** [comment]
Corresponds to https://github.com/DataDog/dd-agent/pull/2245

**Comment by olivielpeau** [comment]
Thanks @tebriel! Will merge as soon as DataDog/omnibus-software#36 is mergeable.

**Comment by tebriel** [comment]
@olivielpeau fixed the other branch (left a comment there as well) thanks!

**Pull request merged**
