### PR TITLE
[deps] use omnibus-software agent release branch

### PR DESCRIPTION
**Pull request by yannmh**
A release branch is forked from master on omnibus-software repository
for each major and minor release. Use it instead of master.

### CODE REVIEW

**Comment by degemer** [comment]
:+1: , but for now the `5.4.3` tag is on master, and `5.4.3` commits are not on the `5.4.x` branch.
Could you also add a default to `master` in https://github.com/DataDog/dd-agent-omnibus/blob/master/omnibus_build.sh#L12 ? This way it won't break anything, and you'll be able to update easily the Jenkins job.

**Comment by yannmh** [comment]
Adding a default `master` value to the branch. We should cherry-pick the changes we made from master to `5.4.x` branch like we do for `dd-agent`.

**Comment by remh** [comment]
Looks good to me.

Don't forget to recreate all the docker images (github.com/DataDog/docker-dd-agent-build* ) if you want this change to be published.

**Comment by yannmh** [comment]
Will do. Thanks!

**Pull request merged**
